#!/bin/bash

# Quick deployment script for Railway
# This script helps you deploy to Railway.app quickly

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║         🚀 Railway Deployment Helper Script                      ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""

# Check if git is initialized
if [ ! -d ".git" ]; then
    echo "📦 Initializing git repository..."
    git init
    git add .
    git commit -m "Initial commit - Appointment Management System"
    echo "✅ Git initialized"
else
    echo "✅ Git already initialized"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 DEPLOYMENT STEPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "STEP 1: Push to GitHub"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "1. Create a new repository on GitHub:"
echo "   https://github.com/new"
echo ""
echo "2. Name it: appointment-management"
echo ""
echo "3. Run these commands:"
echo ""
echo "   git remote add origin https://github.com/YOUR_USERNAME/appointment-management.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
read -p "Press Enter when you've pushed to GitHub..."

echo ""
echo "STEP 2: Deploy Backend on Railway"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "1. Go to: https://railway.app/"
echo "2. Click 'Start a New Project'"
echo "3. Choose 'Deploy from GitHub repo'"
echo "4. Select your repository"
echo "5. Railway will auto-detect Node.js and deploy"
echo ""
echo "6. Add Environment Variables in Railway:"
echo "   Click your service → Variables tab → Add:"
echo ""
echo "   PORT=5000"
echo "   NODE_ENV=production"
echo "   MONGODB_URI=<your MongoDB Atlas connection string>"
echo "   GOOGLE_CLIENT_ID=<your Google client ID>"
echo "   GOOGLE_CLIENT_SECRET=<your Google client secret>"
echo "   GOOGLE_REFRESH_TOKEN=<your Google refresh token>"
echo "   GOOGLE_REDIRECT_URI=https://YOUR-RAILWAY-URL/api/auth/google/callback"
echo "   GOOGLE_CALENDAR_ID=primary"
echo "   TIMEZONE=America/New_York"
echo ""
read -p "Press Enter when backend is deployed..."

echo ""
echo "STEP 3: Get Your Backend URL"
echo "─────────────────────────────────────────────────────────────"
echo ""
read -p "Enter your Railway backend URL (e.g., https://xxx.railway.app): " BACKEND_URL
echo ""
echo "✅ Backend URL saved: $BACKEND_URL"

echo ""
echo "STEP 4: Deploy Frontend on Vercel"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "1. Go to: https://vercel.com/new"
echo "2. Import your GitHub repository"
echo "3. Configure:"
echo "   - Root Directory: frontend"
echo "   - Framework: Create React App"
echo ""
echo "4. Add Environment Variable:"
echo "   REACT_APP_API_URL=$BACKEND_URL/api"
echo ""
echo "5. Click 'Deploy'"
echo ""
read -p "Press Enter when frontend is deployed..."

echo ""
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║              ✅ DEPLOYMENT COMPLETE! ✅                           ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "Your application is now online!"
echo ""
echo "Backend API: $BACKEND_URL"
echo "Health Check: $BACKEND_URL/api/health"
echo ""
echo "Test your API:"
echo "  curl $BACKEND_URL/api/health"
echo ""
echo "🎉 Your appointment management system is live!"
echo ""

